### ISSUE TITLE
some message from yash

### ISSUE THREAD

**Issue by TalsaniyaYash2005** [dhruv-2015/BCA-PC-SAM-1#1]
ka dhula kai kam hoy to keje.
issue to nathi ne.

**Comment by TalsaniyaYash2005** [comment]
comment close no karto ho samji gayo.

**Comment by dhruv-2015** [comment]
Khoti gand sari karma

**Comment by TalsaniyaYash2005** [comment]
> Khoti gand sari karma

Ava apsabdo na bolay dhruv.
